#pragma once

#define LOGIC_GRID_SIZE_IN_CELL 17
#define GRAPHIC_CELL_SIZE_IN_PIXELS 40

#define GRAPHIC_SNAKE_COLOUR_HEAD 255, 0, 0, 255

#define UP 0
#define DOWN 1
#define LEFT 2
#define RIGHT 3

#define PLAYGROUND_HEIGHT 600
#define PLAYGROUND_WIDTH 800

#define FPS_LIMIT 250
